### ISSUE TITLE
Failing error handling

### ISSUE THREAD

**Issue by NodyHub** [NodyHub/fifi#14]
Thats a bug!
```
022/05/04 06:55:13 ERROR (0): Get "https://<snip>/sales-accelerator/oidc/logoutcallback": dial tcp: lookup <snip> on 1.1.1.1:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x634924]

goroutine 7 [running]:
main.performRequest(0xc00007ea00, {0xc000b37950, 0x48})
	/home/runner/work/fifi/fifi/main.go:210 +0x544
main.getAllSignatures.func1(0x0?, 0xc00007ea00, 0x0?, 0xc00000c0a8, 0x0)
	/home/runner/work/fifi/fifi/main.go:291 +0x192
created by main.getAllSignatures
	/home/runner/work/fifi/fifi/main.go:283 +0x37d
```

**Comment by NodyHub** [comment]
fixed
